Investigate bug with TUI progress bar (vibe-kanban f5b1ff27)
When a call to yt-dlp fails, ie. "Your IP address is blocked from accessing this post", the failed counter did not increase.

Now, I'm not sure if this was because the file was already downloaded or not, but it's possibly worth investigating to make sure we're tracking failures appropriately.

<error>
[generic] Extracting URL: https://www.tiktokv.com/share/video/7576483608999775502/

                                                                                                                    [generic] 7576483608999775502: Downloading webpage

                                                                                                                    [redirect] Following redirect to https://www.tiktok.com/@/video/7576483608999775502/

                                                                                                                    [TikTok] Extracting URL: https://www.tiktok.com/@/video/7576483608999775502/
                                                                                                                    [TikTok] 7576483608999775502: Downloading webpage

ERROR: [TikTok] 7576483608999775502: Your IP address is blocked from accessing this post
</error>